// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5O0TBXF9zN7hoktiYx5_aYXCcccUT0iM',
    appId: '1:589935664354:web:fc17ef63463381a0e712bb',
    messagingSenderId: '589935664354',
    projectId: 'spotifynara01',
    authDomain: 'spotifynara01.firebaseapp.com',
    storageBucket: 'spotifynara01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjehM7vkz7UOPzj3gevmjEG-qgTS1Hag',
    appId: '1:589935664354:android:cdd02ae22c62ed53e712bb',
    messagingSenderId: '589935664354',
    projectId: 'spotifynara01',
    storageBucket: 'spotifynara01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs1kn07psL1jMbiVRaPgBANmjo08ND0Tg',
    appId: '1:589935664354:ios:63497501c6654c43e712bb',
    messagingSenderId: '589935664354',
    projectId: 'spotifynara01',
    storageBucket: 'spotifynara01.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs1kn07psL1jMbiVRaPgBANmjo08ND0Tg',
    appId: '1:589935664354:ios:63497501c6654c43e712bb',
    messagingSenderId: '589935664354',
    projectId: 'spotifynara01',
    storageBucket: 'spotifynara01.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5O0TBXF9zN7hoktiYx5_aYXCcccUT0iM',
    appId: '1:589935664354:web:a61eb72e5170c577e712bb',
    messagingSenderId: '589935664354',
    projectId: 'spotifynara01',
    authDomain: 'spotifynara01.firebaseapp.com',
    storageBucket: 'spotifynara01.firebasestorage.app',
  );
}
